<a href="https://colab.research.google.com/github/JuanCOD001116/Proyecto-Modelos/blob/main/02%20-%20preprocesado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Getting Kaggle's Data

In [93]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '.'
!chmod 600 ./kaggle.json
!kaggle competitions download -c udea-ai-4-eng-20251-pruebas-saber-pro-colombia

udea-ai-4-eng-20251-pruebas-saber-pro-colombia.zip: Skipping, found more recently modified local copy (use --force to force download)

In [94]:
!unzip udea*.zip > /dev/null

replace submission_example.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
replace test.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
replace train.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y

In [95]:
!wc *.csv

   296787    296787   4716673 submission_example.csv
   296787   4565553  59185250 test.csv
   692501  10666231 143732449 train.csv
  1286075  15528571 207634372 total

In [96]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder

z = pd.read_csv("train.csv")
print ("shape of loaded dataframe", z.shape)

shape of loaded dataframe (692500, 21)

In [97]:
z.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,ENFERMERIA,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,DERECHO,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,MERCADEO Y PUBLICIDAD,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,ADMINISTRACION DE EMPRESAS,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,PSICOLOGIA,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

#Inspection data#
Revisamos los registros vacios de cada columna.

In [98]:
data_fixed = z.copy()

In [99]:
k = data_fixed.isna().sum()
k[k!=0]

ESTU_VALORMATRICULAUNIVERSIDAD     6287
ESTU_HORASSEMANATRABAJA           30857
FAMI_ESTRATOVIVIENDA              32137
FAMI_TIENEINTERNET                26629
FAMI_EDUCACIONPADRE               23178
FAMI_TIENELAVADORA                39773
FAMI_TIENEAUTOMOVIL               43623
ESTU_PAGOMATRICULAPROPIO           6498
FAMI_TIENECOMPUTADOR              38103
FAMI_TIENEINTERNET.1              26629
FAMI_EDUCACIONMADRE               23664
dtype: int64

## Cleaning ESTU_PRGM_ACADEMICO column

Usamos la función LaberEncoder para transformar los datos de la columnna ESTU_PRGM_ACADEMICO a valores enteros usando etiquetas.

In [100]:
def cleaning_programa_academico(data_fixed):
  label_encoder = LabelEncoder()
  data_fixed['ESTU_PRGM_ACADEMICO'] = label_encoder.fit_transform(data_fixed['ESTU_PRGM_ACADEMICO'])

In [101]:
cleaning_programa_academico(data_fixed)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,BOGOTÁ,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,249,ATLANTICO,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,819,BOGOTÁ,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,14,SANTANDER,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,907,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

## Cleaning ESTU_PRGM_DEPARTAMENTO column

Usamos igualmente LaberEncoder para transformar el Departamento a un número entero.

In [102]:
def cleaning_departamento(data_fixed):
  label_encoder = LabelEncoder()
  data_fixed['ESTU_PRGM_DEPARTAMENTO'] = label_encoder.fit_transform(data_fixed['ESTU_PRGM_DEPARTAMENTO'])

In [103]:
cleaning_departamento(data_fixed)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,Entre 5.5 millones y menos de 7 millones,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,249,3,Entre 2.5 millones y menos de 4 millones,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,819,4,Entre 2.5 millones y menos de 4 millones,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,14,26,Entre 4 millones y menos de 5.5 millones,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,907,1,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

## Cleaning ESTU_VALORMATRICULAUNIVERSIDAD column

Usamos un DataFrame para reemplazar cada rango en su media. Para el rango 'NAN' usamos los valores de media y desviación estándar y usamos una muestra de la distribución normal para reemplazar en estos datos, lo que nos permite sustituir estos valores sin que afecten los demás valores.

In [104]:
def cleaning_matricula(data_fixed):
    valores_matricula = {
        'Entre 5.5 millones y menos de 7 millones': 6.25,
        'Entre 2.5 millones y menos de 4 millones': 3.25,
        'Entre 4 millones y menos de 5.5 millones': 4.75,
        'Más de 7 millones': 7.0,
        'Entre 1 millón y menos de 2.5 millones': 1.75,
        'Entre 500 mil y menos de 1 millón': 0.75,
        'Menos de 500 mil': 0.25,
        'No pagó matrícula': 0,
    }
    data_fixed['ESTU_VALORMATRICULAUNIVERSIDAD'] = data_fixed['ESTU_VALORMATRICULAUNIVERSIDAD'].map(valores_matricula)
    mean = data_fixed['ESTU_VALORMATRICULAUNIVERSIDAD'].mean()
    std = data_fixed['ESTU_VALORMATRICULAUNIVERSIDAD'].std()
    sample = np.random.normal(mean, std, data_fixed['ESTU_VALORMATRICULAUNIVERSIDAD'].isna().sum())
    data_fixed.loc[data_fixed['ESTU_VALORMATRICULAUNIVERSIDAD'].isna(), 'ESTU_VALORMATRICULAUNIVERSIDAD'] = sample

In [105]:
cleaning_matricula(data_fixed)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,6.25,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,249,3,3.25,0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,819,4,3.25,Más de 30 horas,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,14,26,4.75,0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,907,1,3.25,Entre 21 y 30 horas,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

## Cleaning ESTU_HORASSEMANATRABAJA column

Realizamos el mismo proceso pero con Horas Semana Trabaja.

In [106]:
def cleaning_horas_trabajo(data_fixed):
    horas_promedio = {
        'Menos de 10 horas': 5,
        '0': 0,
        'Más de 30 horas': 35,
        'Entre 21 y 30 horas': (21 + 30) / 2,
        'Entre 11 y 20 horas': (11 + 20) / 2
    }
    data_fixed['ESTU_HORASSEMANATRABAJA'] = data_fixed['ESTU_HORASSEMANATRABAJA'].map(horas_promedio)
    mean = data_fixed['ESTU_HORASSEMANATRABAJA'].mean()
    std = data_fixed['ESTU_HORASSEMANATRABAJA'].std()
    sample = np.random.normal(mean, std, data_fixed['ESTU_HORASSEMANATRABAJA'].isna().sum())
    data_fixed.loc[data_fixed['ESTU_HORASSEMANATRABAJA'].isna(), 'ESTU_HORASSEMANATRABAJA'] = sample

In [107]:
cleaning_horas_trabajo(data_fixed)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,6.25,5.0,Estrato 3,Si,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,249,3,3.25,0.0,Estrato 3,No,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,819,4,3.25,35.0,Estrato 3,Si,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,14,26,4.75,0.0,Estrato 4,Si,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,907,1,3.25,25.5,Estrato 3,Si,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

## Cleaning FAMI_ESTRATOVIVIENDA column

Para la categorias seleccionadas usamos LabelEncoder para convertirlo en un enterno, para los valores 'NAN', usamos la moda de la columna Estrato Vivienda.

In [128]:
def cleaning_estrato(data_fixed):
  moda = data_fixed['FAMI_ESTRATOVIVIENDA'].mode()[0]
  data_fixed['FAMI_ESTRATOVIVIENDA'] = data_fixed['FAMI_ESTRATOVIVIENDA'].fillna(moda)
  print("la moda es",moda)
  label_encoder = LabelEncoder()
  data_fixed['FAMI_ESTRATOVIVIENDA'] = label_encoder.fit_transform(data_fixed['FAMI_ESTRATOVIVIENDA'])

In [129]:
cleaning_estrato(data_fixed)
data_fixed.head()

la moda es 1

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,6.25,5.0,2,1,5,Si,...,N,0,Si,Si,9,2,0.322,0.208,0.310,0.267
1,645256,20212,249,3,3.25,0.0,2,0,6,Si,...,N,0,Si,No,5,0,0.311,0.215,0.292,0.264
2,308367,20203,819,4,3.25,35.0,2,1,4,Si,...,N,0,No,Si,4,0,0.297,0.214,0.305,0.264
3,470353,20195,14,26,4.75,0.0,3,1,-1,Si,...,N,0,Si,Si,4,3,0.485,0.172,0.252,0.190
4,989032,20212,907,1,3.25,25.5,2,1,2,Si,...,N,0,Si,Si,2,1,0.316,0.232,0.285,0.294

## Cleaning FAMI_TIENEINTERNET column

Primero reemplazamos los 'NAN' en 'Sin  información'. Utilizamos un DataFrame para registrar las categorias en números enteros. 'Si' lo tomamos como un 1, 'No' lo tomamos como 0 y 'Sin información' como un -1.

In [110]:
def cleaning_internet(data_fixed):
    data_fixed['FAMI_TIENEINTERNET'] = data_fixed['FAMI_TIENEINTERNET'].fillna('Sin Información')
    data_fixed['FAMI_TIENEINTERNET'] = data_fixed['FAMI_TIENEINTERNET'].map({
        'Si': 1,
        'No': 0,
        'Sin Información': -1
    })

In [111]:
cleaning_internet(data_fixed)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,6.25,5.0,2,1,Técnica o tecnológica incompleta,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,249,3,3.25,0.0,2,0,Técnica o tecnológica completa,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,819,4,3.25,35.0,2,1,Secundaria (Bachillerato) completa,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,14,26,4.75,0.0,3,1,No sabe,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,907,1,3.25,25.5,2,1,Primaria completa,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

## Cleaning FAMI_EDUCACIONPADRE column

Primero, reemplazamos los valores 'NAN' con 'Sin Información', luego, reemplazamos 'No sabe', 'No Aplica' y 'Sin información' a -1-. Por último, usamos OrdinalEncoder para registrar por orden cada valor de la lista Levels a un entero y reemplazarlo en la columna.

In [112]:
def cleaning_padre(data_fixed):
    data_fixed['FAMI_EDUCACIONPADRE'] = data_fixed['FAMI_EDUCACIONPADRE'].fillna('Sin Información')
    data_fixed['FAMI_EDUCACIONPADRE'] = data_fixed['FAMI_EDUCACIONPADRE'].replace({
        'No sabe': -1, 'No Aplica': -1, 'Sin Información': -1
    })
    levels = ['Ninguno', 'Primaria incompleta', 'Primaria completa',
              'Secundaria (Bachillerato) incompleta', 'Secundaria (Bachillerato) completa',
              'Técnica o tecnológica incompleta', 'Técnica o tecnológica completa',
              'Educación profesional incompleta', 'Educación profesional completa',
              'Postgrado']
    mask = data_fixed['FAMI_EDUCACIONPADRE'] != -1
    encoder = OrdinalEncoder(categories=[levels])
    data_fixed.loc[mask, 'FAMI_EDUCACIONPADRE'] = encoder.fit_transform(data_fixed.loc[mask, ['FAMI_EDUCACIONPADRE']])
    data_fixed['FAMI_EDUCACIONPADRE'] = data_fixed['FAMI_EDUCACIONPADRE'].astype(int)

In [113]:
cleaning_padre(data_fixed)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,6.25,5.0,2,1,5,Si,...,N,No,Si,Si,Postgrado,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,249,3,3.25,0.0,2,0,6,Si,...,N,No,Si,No,Técnica o tecnológica incompleta,bajo,0.311,0.215,0.292,0.264
2,308367,20203,819,4,3.25,35.0,2,1,4,Si,...,N,No,No,Si,Secundaria (Bachillerato) completa,bajo,0.297,0.214,0.305,0.264
3,470353,20195,14,26,4.75,0.0,3,1,-1,Si,...,N,No,Si,Si,Secundaria (Bachillerato) completa,alto,0.485,0.172,0.252,0.190
4,989032,20212,907,1,3.25,25.5,2,1,2,Si,...,N,No,Si,Si,Primaria completa,medio-bajo,0.316,0.232,0.285,0.294

## Cleaning FAMI_EDUCACIONMADRE column

Realizamos lo mismo que el la columna Educación Padre.

In [114]:
def cleaning_madre(data_fixed):
    data_fixed['FAMI_EDUCACIONMADRE'] = data_fixed['FAMI_EDUCACIONMADRE'].fillna('Sin Información')
    data_fixed['FAMI_EDUCACIONMADRE'] = data_fixed['FAMI_EDUCACIONMADRE'].replace({
        'No sabe': -1, 'No Aplica': -1, 'Sin Información': -1
    })
    levels = ['Ninguno', 'Primaria incompleta', 'Primaria completa',
              'Secundaria (Bachillerato) incompleta', 'Secundaria (Bachillerato) completa',
              'Técnica o tecnológica incompleta', 'Técnica o tecnológica completa',
              'Educación profesional incompleta', 'Educación profesional completa',
              'Postgrado']
    mask = data_fixed['FAMI_EDUCACIONMADRE'] != -1
    encoder = OrdinalEncoder(categories=[levels])
    data_fixed.loc[mask, 'FAMI_EDUCACIONMADRE'] = encoder.fit_transform(data_fixed.loc[mask, ['FAMI_EDUCACIONMADRE']])
    data_fixed['FAMI_EDUCACIONMADRE'] = data_fixed['FAMI_EDUCACIONMADRE'].astype(int)

In [115]:
cleaning_madre(data_fixed)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,6.25,5.0,2,1,5,Si,...,N,No,Si,Si,9,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,249,3,3.25,0.0,2,0,6,Si,...,N,No,Si,No,5,bajo,0.311,0.215,0.292,0.264
2,308367,20203,819,4,3.25,35.0,2,1,4,Si,...,N,No,No,Si,4,bajo,0.297,0.214,0.305,0.264
3,470353,20195,14,26,4.75,0.0,3,1,-1,Si,...,N,No,Si,Si,4,alto,0.485,0.172,0.252,0.190
4,989032,20212,907,1,3.25,25.5,2,1,2,Si,...,N,No,Si,Si,2,medio-bajo,0.316,0.232,0.285,0.294

## Cleaning ESTU_PAGOMATRICULAPROPIO column

Realizamos el mismo proceso que en la columna Tiene Internet.

In [116]:
def cleaning_pago(data_fixed):
    data_fixed['ESTU_PAGOMATRICULAPROPIO'] = data_fixed['ESTU_PAGOMATRICULAPROPIO'].fillna('Sin Información')
    data_fixed['ESTU_PAGOMATRICULAPROPIO'] = data_fixed['ESTU_PAGOMATRICULAPROPIO'].map({
        'Si': 1,
        'No': 0,
        'Sin Información': -1
    })

In [117]:
cleaning_pago(data_fixed)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,6.25,5.0,2,1,5,Si,...,N,0,Si,Si,9,medio-alto,0.322,0.208,0.310,0.267
1,645256,20212,249,3,3.25,0.0,2,0,6,Si,...,N,0,Si,No,5,bajo,0.311,0.215,0.292,0.264
2,308367,20203,819,4,3.25,35.0,2,1,4,Si,...,N,0,No,Si,4,bajo,0.297,0.214,0.305,0.264
3,470353,20195,14,26,4.75,0.0,3,1,-1,Si,...,N,0,Si,Si,4,alto,0.485,0.172,0.252,0.190
4,989032,20212,907,1,3.25,25.5,2,1,2,Si,...,N,0,Si,Si,2,medio-bajo,0.316,0.232,0.285,0.294

## Converting target column

Tomamos cada categoria como un entero y  mapeamos su valor en la columna. 'alto' lo tomamos como un 3, 'bajo' como un 0, 'medio-bajo' como un 1 y 'medio-alto' como un 2.

In [118]:
def cleaning_rendimiento(data_fixed):
  rmap = {'alto': 3, 'bajo':0, 'medio-bajo':1, 'medio-alto':2}
  data_fixed['RENDIMIENTO_GLOBAL'] = data_fixed['RENDIMIENTO_GLOBAL'].map(rmap)

In [119]:
cleaning_rendimiento(data_fixed)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,6.25,5.0,2,1,5,Si,...,N,0,Si,Si,9,2,0.322,0.208,0.310,0.267
1,645256,20212,249,3,3.25,0.0,2,0,6,Si,...,N,0,Si,No,5,0,0.311,0.215,0.292,0.264
2,308367,20203,819,4,3.25,35.0,2,1,4,Si,...,N,0,No,Si,4,0,0.297,0.214,0.305,0.264
3,470353,20195,14,26,4.75,0.0,3,1,-1,Si,...,N,0,Si,Si,4,3,0.485,0.172,0.252,0.190
4,989032,20212,907,1,3.25,25.5,2,1,2,Si,...,N,0,Si,Si,2,1,0.316,0.232,0.285,0.294

## Function with the complete cleaning

Importamos las librearias y creamos una función principal donde llamamos las funciones cleaning para limpiar cada columna y tener un Dataset con solo números reales.

In [120]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np

def data_cleaning(data):
    data_fixed = data.copy()
    cleaning_programa_academico(data_fixed)
    cleaning_departamento(data_fixed)
    cleaning_matricula(data_fixed)
    cleaning_horas_trabajo(data_fixed)
    cleaning_estrato(data_fixed)
    cleaning_internet(data_fixed)
    cleaning_padre(data_fixed)
    cleaning_madre(data_fixed)
    cleaning_pago(data_fixed)
    if 'RENDIMIENTO_GLOBAL' in data_fixed.columns:
      cleaning_rendimiento(data_fixed)
    return data_fixed

In [121]:
data_fixed = data_cleaning(z)
data_fixed.head()

,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_TIENELAVADORA,...,ESTU_PRIVADO_LIBERTAD,ESTU_PAGOMATRICULAPROPIO,FAMI_TIENECOMPUTADOR,FAMI_TIENEINTERNET.1,FAMI_EDUCACIONMADRE,RENDIMIENTO_GLOBAL,coef_1,coef_2,coef_3,coef_4
0,904256,20212,300,4,6.25,5.0,2,1,5,Si,...,N,0,Si,Si,9,2,0.322,0.208,0.310,0.267
1,645256,20212,249,3,3.25,0.0,2,0,6,Si,...,N,0,Si,No,5,0,0.311,0.215,0.292,0.264
2,308367,20203,819,4,3.25,35.0,2,1,4,Si,...,N,0,No,Si,4,0,0.297,0.214,0.305,0.264
3,470353,20195,14,26,4.75,0.0,3,1,-1,Si,...,N,0,Si,Si,4,3,0.485,0.172,0.252,0.190
4,989032,20212,907,1,3.25,25.5,2,1,2,Si,...,N,0,Si,Si,2,1,0.316,0.232,0.285,0.294